services:
  configarr:
    image: configarr:test
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/app/config
      - ./dockerrepos:/app/repos
      - ./custom/cfs:/app/cfs
      - ./custom/templates:/app/templates

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.8
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.7.0
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  sonarr:
  radarr:
