services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.2
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
      - ${PWD}/sonarr.xml:/config/config.xml:rw
    ports:
      - 6500:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.3.6
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr:/config
      - ${PWD}/radarr.xml:/config/config.xml:rw
    ports:
      - 6501:7878
    restart: unless-stopped

networks:
  configarr-full:
    name: configarr-full

volumes:
  sonarr:
  radarr:
